apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::137753204288:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12IUO3QANT4SQ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-31T03:00:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2027"
  uid: fd2e8452-323c-4fae-b12e-371e0fc9126e
